### ISSUE TITLE
server-status on horizon public available

### ISSUE THREAD

**Issue by flyersa** [osism/issues#599] opened 2023-07-18 08:55 UTC
Hi,

we noticed that /server-status is by default enabled on horizon on all installations. I think thats something that should be disabled by default as it can expose internal informations about environments.

**Comment by berendt** [comment] 2023-07-18 09:29
There has been an open issue in Kolla for years. I think I had even opened a review for it. If I remember correctly, it was intended that way and if you don't want it, you should block it with the load balacner in front of it.

There is a newer one still opened at the moment: https://bugs.launchpad.net/kolla-ansible/+bug/1996913

There is a workaround listed in there. We can try this again as a review and backport independently.

**Comment by berendt** [comment] 2023-07-18 09:47
Looks like this is a private issue. I will prepare a review later this day.

**Comment by berendt** [comment] 2023-07-19 17:21
https://review.opendev.org/c/openstack/kolla-ansible/+/888943

**Comment by berendt** [comment] 2024-01-14 09:18
That‘s done. Changed merged upstream. Backport available for stable/zed & stable/2023.1.

**Closed by berendt** 2024-01-14 09:18 UTC
