### ISSUE TITLE
HaproxyServerDown backend=ceph_dashboard

### ISSUE THREAD

**Issue by Nils98Ar** [osism/issues#541] opened 2023-06-02 09:25 UTC
We have three Control Nodes that are running the ceph-dashboard.

For `server=control02` und `server=control03` we see HaproxyServerDown alerts for `instance=control01`, `instance=control02` and `instance=control03` (so each control node instance).

We don't see alerts with server=control01.

HaProxy-Config for ceph-dashboard is:
```
listen ceph_dashboard
  option httpchk
  http-check expect status 200
  {{ "bind %s:%s %s"|e|format(kolla_internal_vip_address, 8140, internal_tls_bind_info)|trim() }}
{% for host in groups['ceph-mgr'] %}
  server {{ hostvars[host]['ansible_hostname'] }} {{ hostvars[host]['internal_address'] }}:7000 check inter 2000 rise 2 fall 5
{% endfor %}
```

May it is related to the http 303 status codes? I am not sure but as control01 returns status code 200 this is the only difference I can find.
```
dragon@manager:~$ curl -sI control01:7000 | grep -E "HTTP|Server"
HTTP/1.1 200 OK
Server: Ceph-Dashboard
dragon@manager:~$ curl -sI control02:7000 | grep -E "HTTP|Server"
HTTP/1.1 303 See Other
Server: Ceph-Dashboard
dragon@manager:~$ curl -sI control03:7000 | grep -E "HTTP|Server"
HTTP/1.1 303 See Other
Server: Ceph-Dashboard
```

**Comment by osfrickler** [comment] 2023-06-02 10:13
I think that this is the expected behaviour, the dashboard is only ever active on one host, the others just send redirects to it. haproxy should only use the active one as working backend.

Not sure how you generate these alerts or if there is an haproxy option that would avoid alerts if a backend is down?

**Comment by Nils98Ar** [comment] 2023-06-02 10:18
I have deployed it via `osism apply prometheus` and `osism apply grafana` with overlay files from https://github.com/osism/kolla-operations.

The haproxy-Config comes from [Cookiecutter](https://github.com/osism/cfg-cookiecutter/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/environments/kolla/files/overlays/haproxy/services.d/haproxy.cfg).

**Comment by berendt** [comment] 2023-06-02 12:29
osism/kolla-operations is out-of-date at the moment. Will be revived in the future. The HAProxy configuration itself is fine.

**Comment by artificial-intelligence** [comment] 2023-06-02 12:32
the rule in question should be: https://github.com/osism/kolla-operations/blob/main/prometheus/haproxy.rules#L27

notice, that I'm currently beginning to overhaul the `kolla-operations` repository.

as a general remark you need to take care that applied alert rules match your operational needs for your specific environment, as our provided alerts can never match every environments specific needs, which are often contradicting each other.

in this case this means: is it even critical for you, if the ceph dashboard is not available, as many operators do not use it at all? if not it would be best to silence or disable this alert rule, e.g. by matching on only specific services you want to alert on.

I'm planning to replace these generic haproxy server/backend alerts with specific alerts per service, such that you can - hopefully - easily disable a single service you don't care about, and make the whole thing in general more configurable by the end user.

e.g. upstream ceph has also a curated list of alerts, but written in [jsonnet](https://jsonnet.org/):

https://github.com/ceph/ceph/blob/main/monitoring/ceph-mixin/prometheus_alerts.libsonnet

notice how upstream ceph has no specific alerts for the dashboard as well, because it's an optional component.

the reworking of the alerts will take some time, unfortunately, so for now I see no easy intermediate solution for you than to refit the alerts to your specific needs manually.

HTH

**Comment by Nils98Ar** [comment] 2023-06-02 12:39
Okay, thank you. I thought that kolla-operations is just not complete anymore regarding ovn etc.

So do you see false alerts in the testbed as well?

**Comment by berendt** [comment] 2023-06-02 12:40
> So do you see false alerts in the testbed as well?

We do not use it there.

**Comment by Nils98Ar** [comment] 2023-06-02 12:41
Okay I see

**Comment by berendt** [comment] 2023-06-04 17:41
Close this as it is currently the expected behavior since it is broken.

**Closed by berendt** 2023-06-04 17:41 UTC
Labels: discussion
