### ISSUE TITLE
Disable OSD restart after osism apply ceph-rgws

### ISSUE THREAD

**Issue by b1knoll** [osism/issues#970] opened 2024-04-17 07:26 UTC
Hello,

after running:

osism apply ceph-rgws

all OSDs get restarted.

This is not neccessary.

Please disable this.

Best,
Marc

**Comment by berendt** [comment] 2024-04-17 07:28
Duplicate of https://github.com/osism/issues/issues/896.

**Closed by berendt** 2024-04-17 07:28 UTC
